export const medicosIniciales = [
  // Cardiólogos
  {
    id: 1,
    nombre_completo: 'Dr. Juan Pérez',
    especialidad: 'Cardiólogo',
    obra_social: 'OSDE',
    telefono: '2234567890',
    email: 'juan.perez@centro.med',
    img: 'img/profesionales/cardiologo_juan.jpg',
  },
  {
    id: 2,
    nombre_completo: 'Dr. Pedro Sánchez',
    especialidad: 'Cardiólogo',
    obra_social: 'Swiss Medical',
    telefono: '2235678901',
    email: 'pedro.sanchez@centro.med',
    img: 'img/profesionales/cardiologo_Pedro.png',
  },
  {
    id: 3,
    nombre_completo: 'Dr. Martina Pereira',
    especialidad: 'Cardiólogo',
    obra_social: 'PAMI',
    telefono: '2236789012',
    email: 'martina.pereira@centro.med',
    img: 'img/profesionales/cardiologa_martina.jpg',
  },
  // Pediatras
  {
    id: 4,
    nombre_completo: 'Dra. Laura Gómez',
    especialidad: 'Pediatra',
    obra_social: 'OSDE',
    telefono: '2237890123',
    email: 'laura.gomez@centro.med',
    img: 'img/profesionales/pediatra_laura.jpg',
  },
  {
    id: 5,
    nombre_completo: 'Dr. Luis Benítez',
    especialidad: 'Pediatra',
    obra_social: 'Galeno',
    telefono: '2238901234',
    email: 'luis.benitez@centro.med',
    img: 'img/profesionales/pediatra_luis.jpg',
  },
  {
    id: 6,
    nombre_completo: 'Dra. María Gonzalez',
    especialidad: 'Pediatra',
    obra_social: 'Swiss Medical',
    telefono: '2239012345',
    email: 'maria.gonzalez@centro.med',
    img: 'img/profesionales/pediatra_maria.jpg',
  },
  // Dermatólogos
  {
    id: 7,
    nombre_completo: 'Dr. Martin Perez',
    especialidad: 'Dermatólogo',
    obra_social: 'OSDE',
    telefono: '2231122334',
    email: 'martin.perez@centro.med',
    img: 'img/profesionales/dermatologo_martin.jpg',
  },
  {
    id: 8,
    nombre_completo: 'Dra. Ana Maria Gimenez',
    especialidad: 'Dermatólogo',
    obra_social: 'IOMA',
    telefono: '2232233445',
    email: 'anamaria.gimenez@centro.med',
    img: 'img/profesionales/dermatologa_ana.jpg',
  },
  {
    id: 9,
    nombre_completo: 'Dr. Victoria Lopez',
    especialidad: 'Dermatólogo',
    obra_social: 'PAMI',
    telefono: '2233344556',
    email: 'victoria.lopez@centro.med',
    img: 'img/profesionales/dermatologa_victoria.jpg',
  },
];
