export const medicosIniciales = [
  {
    id: 1,
    nombre_completo: 'Dr. Juan Pérez',
    especialidad_id: 1,
    obras_sociales: [1],
    telefono: '2234567890',
    email: 'juan.perez@centro.med',
    descripcion:
      'Especialista en cardiología intervencionista con más de 15 años de experiencia.',
    valor_consulta: 8500.5,
    img: 'img/profesionales/cardiologo_juan.jpg',
  },
  {
    id: 2,
    nombre_completo: 'Dr. Pedro Sánchez',
    especialidad_id: 1,
    obras_sociales: [2],
    telefono: '2235678901',
    email: 'pedro.sanchez@centro.med',
    descripcion: 'Cardiólogo especializado en arritmias y marcapasos.',
    valor_consulta: 9200.0,
    img: 'img/profesionales/cardiologo_Pedro.png',
  },
  {
    id: 3,
    nombre_completo: 'Dr. Martina Pereira',
    especialidad_id: 1,
    obras_sociales: [3],
    telefono: '2236789012',
    email: 'martina.pereira@centro.med',
    descripcion:
      'Cardióloga con enfoque en prevención y rehabilitación cardíaca.',
    valor_consulta: 7800.0,
    img: 'img/profesionales/cardiologa_martina.jpg',
  },
  {
    id: 4,
    nombre_completo: 'Dra. Laura Gómez',
    especialidad_id: 3,
    obras_sociales: [1],
    telefono: '2237890123',
    email: 'laura.gomez@centro.med',
    descripcion:
      'Pediatra especializada en neonatología y seguimiento del desarrollo infantil.',
    valor_consulta: 6500.0,
    img: 'img/profesionales/pediatra_laura.jpg',
  },
  {
    id: 5,
    nombre_completo: 'Dr. Luis Benítez',
    especialidad_id: 3,
    obras_sociales: [2],
    telefono: '2238901234',
    email: 'luis.benitez@centro.med',
    descripcion:
      'Pediatra con experiencia en enfermedades respiratorias infantiles.',
    valor_consulta: 6200.0,
    img: 'img/profesionales/pediatra_luis.jpg',
  },
  {
    id: 6,
    nombre_completo: 'Dra. María Gonzalez',
    especialidad_id: 3,
    obras_sociales: [2],
    telefono: '2239012345',
    email: 'maria.gonzalez@centro.med',
    descripcion:
      'Pediatra general con enfoque en nutrición y vacunación infantil.',
    valor_consulta: 6000.0,
    img: 'img/profesionales/pediatra_maria.jpg',
  },
  {
    id: 7,
    nombre_completo: 'Dr. Martin Perez',
    especialidad_id: 2,
    obras_sociales: [1],
    telefono: '2231122334',
    email: 'martin.perez@centro.med',
    descripcion:
      'Dermatólogo especializado en cáncer de piel y cirugía dermatológica.',
    valor_consulta: 7500.0,
    img: 'img/profesionales/dermatologo_martin.jpg',
  },
  {
    id: 8,
    nombre_completo: 'Dra. Ana Maria Gimenez',
    especialidad_id: 2,
    obras_sociales: [3],
    telefono: '2232233445',
    email: 'anamaria.gimenez@centro.med',
    descripcion:
      'Dermatóloga cosmética y estética con amplia experiencia en tratamientos faciales.',
    valor_consulta: 8200.0,
    img: 'img/profesionales/dermatologa_ana.jpg',
  },
  {
    id: 9,
    nombre_completo: 'Dr. Victoria Lopez',
    especialidad_id: 2,
    obras_sociales: [3],
    telefono: '2233344556',
    email: 'victoria.lopez@centro.med',
    descripcion:
      'Dermatóloga especialista en enfermedades autoinmunes de la piel.',
    valor_consulta: 7000.0,
    img: 'img/profesionales/dermatologa_victoria.jpg',
  },
];
